server:
  port: 2102
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0  #采样频率
    web:
      enabled: true
  redis:
    host: 127.0.0.1
  cloud:
    stream:
      bindings:
        output: 
          destination: test #消息中间件的主题名
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092         #Kafka的消息中间件服务器
          #zk-nodes: localhost:2181        #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8260/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
security:
  oauth2:
    client:
      client-id: AppID
      client-secret: secretID
      user-authorization-uri: http://localhost:9000/oauth/authorize
      access-token-uri: http://localhost:9000/oauth/token
    resource:
      id: AppID
      user-info-uri: http://localhost:9000/user
    authorization:
      check-token-access: http://localhost:9000/oauth/check_token
howell:
  test: '测试3'
