server:
  port: 2101
spring:
  application:
    name: user-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8260/eureka
howell:
  test: '测试'
