server:
  port: 2102
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:8240/
  sleuth:
    sampler:
      probability: 1.0
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8260/eureka
howell:
  test: '测试'
